coreos-koji-tagger: catch koji.AuthError exception
In our logic to determine if we're still logged in we need to catch
the koji.AuthError exception and pass so that we can fall through to
the code that does the login.

This is a followup to d46a3a1 which was part of
https://github.com/coreos/fedora-coreos-releng-automation/issues/46

Here is the exception you'll see:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 300, in process_message
    self.koji_login()
  File "/usr/lib/python3.7/site-packages/coreos_koji_tagger.py", line 451, in koji_login
    if self.koji_client.getLoggedInUser():
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2135, in __call__
    return self.__func(self.__name, args, opts)
  File "/usr/lib/python3.7/site-packages/koji/__init__.py", line 2650, in _callMethod
    raise err
koji.AuthError: Invalid session or bad credentials
```